const state = { user: null, data: null };
const USER_KEY = 'df_user_public_id';
const NAME_KEY = 'df_user_display_name';
function $(id){return document.getElementById(id)}
function userId(){return localStorage.getItem(USER_KEY)||''}
function setTab(name){document.querySelectorAll('.fz-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.fz-tab-panel').forEach(p=>p.classList.toggle('active',p.id===name));}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.tab)));
document.querySelectorAll('[data-open]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();setTab(a.dataset.open)}));
$('loginForm').addEventListener('submit', async e=>{e.preventDefault();const name=$('loginName').value.trim()||'Guest Manager';const d=await dfFetch('/api/public/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({display_name:name})});localStorage.setItem(USER_KEY,d.user.public_id);localStorage.setItem(NAME_KEY,d.user.display_name);await load();});
function cardHtml(c){return `<div class="df-card"><div class="rating">${c.base_stat||90}</div>${c.player_image?`<img src="${esc(c.player_image)}">`:'<div class="text-5xl">⚽</div>'}<b>${esc(c.player_name||c.title||'Player')}</b><br><span class="muted">${esc(c.rarity||'Rare')} · #${c.id||''}</span></div>`}
function predictionHtml(m, full=false){const opts=(m.options||[]).map(o=>`<button onclick="submitPrediction(${m.id}, '${esc(o.option_key)}', '${esc(o.option_label)}', this)">${esc(o.option_label)}</button>`).join('');return `<div class="prediction-card"><div class="flex justify-between gap-3"><div><b>${esc(m.title)}</b><p class="muted">${esc(m.home_team||'')} ${m.home_team?'vs':''} ${esc(m.away_team||'')}</p></div><span class="pill">${m.lock_at?fmtTime(m.lock_at):'Open'}</span></div><div class="prediction-options">${opts||'<span class="muted">Options will appear soon.</span>'}</div><div class="reward-line"><span>🪙 ${m.coin_reward||10} coins</span><span>⭐ ${m.base_points||10} pts</span><span>💎 ${m.shard_reward||0} shards</span></div></div>`}
async function submitPrediction(marketId, optionKey, optionLabel, btn){if(!userId()){alert('Please login first so your points can be stored.');return;} await dfFetch('/api/public/predictions/submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({user_public_id:userId(),market_id:marketId,option_key:optionKey,option_label:optionLabel})});btn.closest('.prediction-options').querySelectorAll('button').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');}
window.submitPrediction=submitPrediction;
function renderSquad(cards=[]){const chosen=cards.slice(0,11);const rows=[chosen.slice(0,3),chosen.slice(3,6),chosen.slice(6,10),chosen.slice(10,11)];return `<div class="pitch-grid">${rows.map(r=>`<div class="pitch-line">${r.map(c=>`<div class="mini-card">${c.player_image?`<img src="${esc(c.player_image)}">`:'⚽'}<b>${esc((c.player_name||'Player').split(' ').slice(-1)[0])}</b><br><span>${c.base_stat||90}</span></div>`).join('')}</div>`).join('')}</div>`}
function renderLeader(rows=[]){return rows.map((r,i)=>`<div class="leader-row ${r.public_id===userId()?'me':''}"><b>${i+1}</b><span>${esc(r.display_name||'Manager')}</span><b>${r.points||0} pts</b></div>`).join('')||'<p class="muted">Leaderboard starts when users score points.</p>'}
function render(){const d=state.data;const s=d.stats||{};$('miniWallet').innerHTML=`🪙 ${s.coins||420}`;$('stats').innerHTML=`<div class="metric">Coins<b>${s.coins||420}</b></div><div class="metric">Rank<b>#${s.rank||'-'}</b></div><div class="metric">Collection Power<b>${s.collection_power||0}</b></div><div class="metric">Cards Owned<b>${s.cards_owned||0}</b></div><div class="metric">Fantasy Points<b>${s.fantasy_points||0}</b></div>`;const markets=d.markets||[];$('predictionList').innerHTML=markets.slice(0,3).map(m=>predictionHtml(m)).join('')||'<p class="muted">No open predictions. Generate daily markets from admin.</p>';$('predictionFull').innerHTML=markets.map(m=>predictionHtml(m,true)).join('')||'<p class="muted">No open predictions.</p>';const cards=d.cards||[];$('topCards').innerHTML=cards.slice(0,4).map(cardHtml).join('')||'<p class="muted">No cards yet.</p>';$('cardDrops').innerHTML=cards.slice(0,4).map(cardHtml).join('');$('cardsFull').innerHTML=cards.map(cardHtml).join('');$('squadPreview').innerHTML=renderSquad(cards);$('teamPitch').innerHTML=renderSquad(cards);$('leaderMini').innerHTML=renderLeader(d.leaderboard||[]);$('leaderFull').innerHTML=renderLeader(d.leaderboard||[]);$('quests').innerHTML=['Make 3 predictions 2/3 · 🪙20','Predict correct scorer 0/1 · 🪙30','Enter fantasy contest 0/1 · 🪙25'].map(x=>`<div class="leader-row"><span>🎯</span><span>${x}</span><b>›</b></div>`).join('');}
async function load(){const qs=userId()?`?user_public_id=${encodeURIComponent(userId())}`:'';state.data=await dfFetch(`/api/public/fantasy-zone${qs}`);if(state.data.user){$('loginName').value=state.data.user.display_name||'';}else if(localStorage.getItem(NAME_KEY)){$('loginName').value=localStorage.getItem(NAME_KEY);}render();}
load().catch(e=>{console.error(e);document.body.insertAdjacentHTML('beforeend','<div class="panel muted fixed bottom-4 right-4">Could not load Fantasy Zone.</div>')});
