let currentSeason="";
const seasonSelect=document.getElementById("seasonSelect"),groupsView=document.getElementById("groupsView"),knockoutsView=document.getElementById("knockoutsView"),groupTab=document.getElementById("groupTab"),knockoutTab=document.getElementById("knockoutTab");
function setTab(name){const g=name==="groups";groupTab.classList.toggle("active",g);knockoutTab.classList.toggle("active",!g);groupsView.classList.toggle("hidden",!g);knockoutsView.classList.toggle("hidden",g);}
function teamRow(t,i){return `<tr><td class="rank">${i+1}</td><td class="team">${flagOrLogo(t)} <span>${esc(t.team_name||t.name)}</span></td><td>${t.played??0}</td><td>${t.won??0}</td><td>${t.drawn??0}</td><td>${t.lost??0}</td><td>${t.goals_for??0}</td><td>${t.goals_against??0}</td><td>${t.goal_difference??0}</td><td class="pts">${t.points??0}</td></tr>`;}
function renderGroups(groups){if(!groups||!groups.length){groupsView.innerHTML=`<div class="df-card">No group-stage table found for this season.</div>`;return;}groupsView.innerHTML=groups.map(g=>`<section class="df-table-block"><h2>${esc(g.group_name)}</h2><table class="df-standings-table"><thead><tr><th></th><th>Team</th><th>MP</th><th>W</th><th>D</th><th>L</th><th>GF</th><th>GA</th><th>GD</th><th>Pts</th></tr></thead><tbody>${(g.teams||[]).map(teamRow).join("")}</tbody></table></section>`).join("");}
function renderRound(title,fixtures){return `<div class="df-ko-round"><h2>${esc(title)}</h2>${(fixtures||[]).map(f=>`<article class="df-ko-card"><div class="date">${esc(f.kickoff_label||f.starting_at||"")}</div><div class="ko-team">${flagOrLogo({logo_url:f.home_logo})}<b>${esc(f.home_team||"TBD")}</b></div><div class="ko-team">${flagOrLogo({logo_url:f.away_logo})}<b>${esc(f.away_team||"TBD")}</b></div>${f.details?`<small>${esc(f.details)}</small>`:""}</article>`).join("")}</div>`;}
function renderKnockouts(rounds){if(!rounds||!rounds.length){knockoutsView.innerHTML=`<div class="df-card">No knockout bracket found for this season.</div>`;return;}knockoutsView.innerHTML=`<div class="df-ko-scroll">${rounds.map(r=>renderRound(r.round_name,r.fixtures)).join("")}</div>`;}
async function loadSeasons(){const data=await apiGet("/api/public/world-cups");const seasons=data.data||data.seasons||[];seasonSelect.innerHTML=seasons.map(s=>`<option value="${esc(s.season_id||s.sportmonks_season_id||s.id)}">${esc(s.year||s.name)}</option>`).join("");currentSeason=seasonSelect.value;}
async function loadPage(){currentSeason=seasonSelect.value;groupsView.innerHTML=`<div class="df-card">Loading groups...</div>`;knockoutsView.innerHTML=`<div class="df-card">Loading bracket...</div>`;const standings=await apiGet(`/api/public/standings?season_id=${encodeURIComponent(currentSeason)}`);renderGroups(standings.groups||standings.data||[]);const bracket=await apiGet(`/api/public/knockouts?season_id=${encodeURIComponent(currentSeason)}`);renderKnockouts(bracket.rounds||[]);}
groupTab.addEventListener("click",()=>setTab("groups"));knockoutTab.addEventListener("click",()=>setTab("knockouts"));seasonSelect.addEventListener("change",loadPage);
(async()=>{try{await loadSeasons();await loadPage();}catch(err){groupsView.innerHTML=`<div class="df-card">Could not load standings: ${esc(err.message)}</div>`;}})();