const params=new URLSearchParams(location.search); const id=params.get('id'); let currentSeason=params.get('season_id');
const resultText=x=>x.won_tournament?'Winner':(x.final_rank?`Finished #${x.final_rank}`:(x.reached_stage||'Played'));
async function loadTeam(){ if(!id) throw new Error('Missing team id'); const qs=currentSeason?`?season_id=${encodeURIComponent(currentSeason)}`:''; const d=await dfFetch(`/api/public/team/${id}${qs}`); currentSeason=d.season_id||currentSeason; const t=d.team; document.title=`${t.name} | DreamFooter`; const selected=(d.world_cups||[]).find(x=>String(x.season_id)===String(currentSeason)); hero.innerHTML=`<div class="flex items-center gap-5"><div class="crest" style="width:82px;height:82px">${logo(t.logo_url,t.name)}</div><div><div class="pill">${selected?.year?`${selected.year} · ${resultText(selected)}`:(t.short_code||'Team')}</div><h1 class="title mt-3">${esc(t.name)}</h1><p class="muted">${selected?'Showing matches and players for this World Cup only.':'World Cup history, fixtures, players and cards.'}</p></div></div>`;
  history.innerHTML=(d.world_cups||[]).length?`<div class="tabs mb-3">${d.world_cups.map(x=>`<button class="pill ${String(x.season_id)===String(currentSeason)?'active':''}" onclick="currentSeason='${x.season_id}';loadTeam()">${x.year||x.season_id} · ${esc(resultText(x))}</button>`).join('')}</div><table class="stat-table"><thead><tr><th>Year</th><th>Result</th><th>MP</th><th>W</th><th>D</th><th>L</th><th>GF</th><th>GA</th><th>GD</th></tr></thead><tbody>${d.world_cups.map(x=>`<tr><td>${x.year||x.season_id}</td><td>${esc(resultText(x))}</td><td>${x.played??0}</td><td>${x.won??0}</td><td>${x.drawn??0}</td><td>${x.lost??0}</td><td>${x.goals_for??0}</td><td>${x.goals_against??0}</td><td>${x.goal_difference??0}</td></tr>`).join('')}</tbody></table>`:'<p class="muted">Historical team stats will appear after rebuild.</p>';
  fixtures.innerHTML=(d.fixtures||[]).map(f=>`<a class="fixture-row" href="/fixture.html?id=${f.sportmonks_fixture_id}"><div>${fmtDate(f.starting_at)}<br><b>${fmtTime(f.starting_at)}</b></div><div><b>${esc(f.home_team||'TBD')} vs ${esc(f.away_team||'TBD')}</b><br><span class="muted">${esc(f.stage_name||'')}</span></div><div>${f.home_score??0} - ${f.away_score??0}</div></a>`).join('')||'<p class="muted">No matches found.</p>';
  const awardHtml=(d.awards||[]).length?`<div class="mb-3 grid gap-2">${d.awards.map(a=>`<div class="pill">${esc(a.award)} · ${esc(a.display_name)} ${a.goals?`(${a.goals} goals)`:''}</div>`).join('')}</div>`:'';
  players.innerHTML=awardHtml+(d.top_players||[]).map(p=>`<a class="player-row" href="/player.html?id=${p.player_id}"><div>${p.image_url?`<img class="h-10 w-10 rounded-full object-cover" src="${esc(p.image_url)}">`:'⚽'}</div><div><b>${esc(p.display_name)}</b><br><span class="muted">${p.goals||0} G · ${p.assists||0} A · ${p.yellow_cards||0} YC · ${p.red_cards||0} RC</span></div><div>›</div></a>`).join('')||'<p class="muted">Player stats will appear after squad import.</p>';
  cards.innerHTML=(d.cards||[]).map(c=>`<div class="player-card"><div class="font-mono text-3xl font-black">${c.base_stat||80}</div><div class="mt-3 grid place-items-center">${c.player_image?`<img src="${esc(c.player_image)}" class="h-16 w-16 rounded-full object-cover">`:'⚽'}</div><b>${esc(c.title||c.player_name)}</b><br><span class="muted">${esc(c.rarity)} · ${esc(c.card_type)}</span></div>`).join('')||'<p class="muted">No cards yet. Run rebuild/generate_cards, then export card_templates for image generation.</p>';
}
loadTeam().catch(e=>{console.error(e);hero.innerHTML='<div class="muted">Could not load team.</div>';});
