const sid = new URLSearchParams(location.search).get('season_id');
const teamStats=t=>`${t.played??0} MP · ${t.won??0}W ${t.drawn??0}D ${t.lost??0}L · GF ${t.goals_for??0} GA ${t.goals_against??0} GD ${t.goal_difference??0}`;
async function boot(){
  if(!sid) throw new Error('Missing season_id');
  const d = await dfFetch(`/api/public/world-cups/${sid}`); const e=d.edition||{}; document.title=`${e.name||e.year||'World Cup'} | DreamFooter`;
  const winner=d.winner||{}; const podium=`<div class="grid gap-3 md:grid-cols-3 mt-5"><div class="panel"><div class="pill">Winner</div><h2 class="text-xl font-black mt-2">${esc(winner.winner_name||'TBD')}</h2></div><div class="panel"><div class="pill">Runner-up</div><h2 class="text-xl font-black mt-2">${esc(winner.runner_up_name||'TBD')}</h2></div><div class="panel"><div class="pill">Third</div><h2 class="text-xl font-black mt-2">${esc((d.teams||[]).find(t=>t.final_rank===3)?.name||'TBD')}</h2></div></div>`;
  hero.innerHTML=`<div class="pill">🏆 ${e.year||sid}</div><h1 class="title mt-4">${esc(e.name||'FIFA World Cup')}</h1><p class="muted mt-2">Winner, podium, team stats, knockout map, groups and impact players.</p><div class="mt-5 flex gap-3 flex-wrap"><a class="btn" href="/schedule.html?season_id=${sid}">Schedule</a><a class="btn" href="/groups.html?season_id=${sid}">Groups</a></div>${podium}`;
  fixtures.innerHTML=`<h3 class="section-title mb-3">Knockout Map</h3>`+((d.knockout||[]).length?(d.knockout||[]).map(f=>`<a class="fixture-row" href="/fixture.html?id=${f.sportmonks_fixture_id}"><div>${fmtDate(f.starting_at)}<br><b>${fmtTime(f.starting_at)}</b></div><div><b>${esc(f.home_team||'TBD')} vs ${esc(f.away_team||'TBD')}</b><br><span class="muted">${esc(f.round_name||f.stage_name||'Knockout')}</span></div><div>${f.home_score??0} - ${f.away_score??0}</div></a>`).join(''):'<p class="muted">Knockout fixtures are not imported yet.</p>')+`<h3 class="section-title mt-6 mb-3">All Fixtures</h3>`+(d.fixtures||[]).slice(0,20).map(f=>`<a class="fixture-row" href="/fixture.html?id=${f.sportmonks_fixture_id}"><div>${fmtDate(f.starting_at)}</div><div><b>${esc(f.home_team||'TBD')} vs ${esc(f.away_team||'TBD')}</b><br><span class="muted">${esc(f.stage_name||f.group_name||'')}</span></div><div>${f.home_score??0} - ${f.away_score??0}</div></a>`).join('');
  teams.innerHTML=`<h3 class="section-title mb-3">Team Stats</h3>`+(d.teams||[]).slice(0,32).map(t=>`<a class="player-row" href="/team.html?id=${t.team_id||t.sportmonks_team_id}&season_id=${sid}"><span>${t.logo_url?`<img class="h-8 w-8 object-contain" src="${esc(t.logo_url)}">`:'🌐'}</span><div><b>${t.final_rank?`#${t.final_rank} `:''}${esc(t.name)}</b><br><span class="muted">${esc(teamStats(t))}</span></div><span>›</span></a>`).join('')+`<h3 class="section-title mt-6 mb-3">Groups</h3>`+(d.groups||[]).map(g=>`<div class="panel mb-3"><b>${esc(g.group_name)}</b><p class="muted">Winner: ${esc((g.teams||[])[0]?.name||'TBD')}</p></div>`).join('');
  const pot=d.awards?.player_of_tournament, fair=d.awards?.fair_play_team;
  players.innerHTML=`<div class="grid gap-2 mb-4"><div class="pill">Player of Tournament: ${esc(pot?.display_name||'TBD')}</div><div class="pill">Golden Boot: ${esc(d.awards?.golden_boot?.display_name||'TBD')}</div><div class="pill">Fair Play Team: ${esc(fair?.name||'TBD')}</div></div>`+(d.top_players||[]).slice(0,20).map(p=>`<a class="player-row" href="/player.html?id=${p.player_id||p.sportmonks_player_id}"><span>${p.image_url?`<img class="h-8 w-8 rounded-full object-cover" src="${esc(p.image_url)}">`:'⚽'}</span><div><b>${esc(p.display_name)}</b><br><span class="muted">${p.goals??0} G · ${p.assists??0} A · ${p.appearances??0} Apps · ${p.yellow_cards??0} YC · ${p.red_cards??0} RC</span></div></a>`).join('') || '<p class="muted">No player stats yet.</p>';
}
boot().catch(e=>{console.error(e); hero.innerHTML='<div class="muted">Could not load this World Cup edition.</div>';});
